version: '2'
services:
    piratesfl-app:
        image: piratesfl
        external_links:
            - piratesfl-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/piratesfl
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    piratesfl-postgresql:
        extends:
            file: postgresql.yml
            service: piratesfl-postgresql
